Fixes a bug with _args being None if no additional argument is manually set
 in create_employers
employer.score = self._fitness_fxn(employer.values, **self._args)
TypeError: abcScore() argument after ** must be a mapping, not NoneType